const tableData = [
    {
      MaterialDocumnet: '5000658879',
      MaterialDocYear: '2023',
      materialDocItem: 'Item 1',
      identification: 'ID123',
      movementType: 'Type A',
      Material: 'Material A',
      Plant: 'Plant 1',
      storageLocation: 'Location 1',
      batch: 'Batch A',
      stockType: 'Type 1',
      supplier: 'Supplier A',
      currency: 'USD',
      amountInLocCur: '100',
      valuationType: 'Type A',
      quantity: 50,
      baseUnitofMeasure: 'kg',
      qtyinunitofentry: '10',
      unitofEntry: 'unit',
      qtyinOPUn: '5',
      orderPriceUnit: 'NOS',
      purchaseOrder: '4500167423',
      Item: '1',
      FiscYearRefDoc: '2022',
      ReferenceDocument: '5000658879',
      ReferenceDocItem: '1',
      MaterialDocItem: '0',
      DeliveryCompleted: 'X',
      Text: 'S035',
      Goodsrecipient: 'p.srinivas',
      ControllingArea: '1000',
      FiscalYear: '2022',
      CompanyCode: '1000',
      Statisticallyrelev: '2',
      ReceivingMaterial: 'one',
      Receivingplant: 'ss',
      Receivingstorloc: 'a',
      ReceivingBatch: 's',
      RestrictedUse: 'q',
      Statkeytfrbatch: 's',
      Spindstocktfr: 'q',
      Movementindicator:  'q',
      Consumption: 'q',
      ReceiptIndicator: 'w',
      GRnonvaluated: '',
      Noofpallets: '',
      WarehouseNumber:  '',
      StorageType: 'q',
      StorageBin: '',
      StockCategory: 'q',
      MovementType: '',
      TRNumber: '1',
      TRItem: '1',
      PostinginWM: '1',
      Intstpostsource: 'q',
      Interimstorpdest: 'q',
      Dynamicstoragebin: '',
      PostingChangeNumber: '1',
      TransferPriority: '1',
      TransferOrderNumber: '1',
      NumberofGRSlips: '1',
      ReasonforMovement: 'q',
      CompliancewithShippingInstr : '',
      ShippingInstr : '',
      RealEstateKey : '',
      CostObject : '',
      ProfitabSegmtNo : '',
      ProfitCenter : '',
      WBSElement : '',
      Network : '',
      Routingnumberforoperations : '',
      Counter : '',
      Orderitemnumber : '',
      Partner : '',
      Commitmentitem : '',
      GLAccount : '',
      Qtyinorderunit : '',
      OrderUnit : '',
      RevGRdespiteIR : '',
      Vendor : '',
      RefSD : '',
      Addittext3 : '',
      TicketDate : '',
      TicketNO : '',
      TicketStatus : '',
      VendorName : '',
      VendorGSTIN : '',
      Remarks : '',
      ExtAmountinLocalCurrency : '',
      SeasoSalesValueincVATnYear : '',
      Promotion : '',
      SeqNoofAccountAssgt : 'f',
      SLEDBBD : 0,
      Internalobjectno : '',
      SalesValue : '',
      PartnerProfitCtr : '',
      Recordtype : '',
      Fund : '',
      FundsCenter : '',
      StockMaterial : '',
      Receivingmaterial : '',
      Quantitystring : '',
      ValueString : '',
      Quantityupdating : '',
      Valueupdating : '',   
      Totalvaluatedstockbeforetheposting  : '',          
      Totlvalbfposting : '2e',
      Pricecontrol : '2e',
      FunctionalArea : '2e',
      Referencedate : '2e',
      SalesvaluewoVAT : '2e',
      ReferenceDate : '2e',
      AutomaticPO : '2e',
      DelNoteQuantity : '2e',
      DeliveryNoteUnit : '2e',
      Specstkvaluation : '2e',
      InspectionStatusinGRDocument : '2e',
      Originallineitem : '2e',
      Altbaseamount : '2e',
      TaxCode : '2e',
      TaxJurisdiction : '2e',
      MPNmaterial : '2e',
      Goodsissuerevaluationperformed : '2e',
      Taxcode : 'wq',
      DateofManufacture : 'wq',
      MatStagingIndicat : 'wq',
      Salesorder : 'wq',
      Salesorderitem : 'wq',
      WBSelement : 'wq',
      Calcnofvalueopen : 'wq',
      AccountingIndicator : 'wq',
      BusinessProcess : 'wq',
      SupplyingVendor : 'wq',
      ActivityType : 'wq',
      Vendorstockvaluation : 'wq',
      Grant : 'wq',
      StockTypeModif : 'wq',
      GTSStockType : 'wq',
      EarmarkedFunds : 'wq',
      DocumentItem : 'wq',
      MultipleAccountAssignment : 'wq',
      TransEventType : 'qqqq',
      PostingDate : 'qqqq',
      EntryDate : 'qqqq',
      TimeofEntry : 'qqqq',
      UserName : 'qqqq',
      Reference : 'qqqq',
      TransactionCode : 'qqqq',
      Delivery : 'qqqq',
      item : 'qqqq',
      StockSegment : 'qqqq',
      ReceivingStockSegment : 'qqqq',
      RequirementSegment : 'qqqq',
      EDStatus : 'qqqq',
      Username : 'qqqq',
      ChangedOn : 'qqqq',
      Time : 'qqqq',
      Ownerofstock : 'qqqq',
      SeasonYear : 'qqqq',
      Season : 'qqqq',
      Collection : 'qqqq',
      Theme : 'qqqq',
      ReceivingIssuingSeasonYear : 'qqqq',      
      ReceivingIssuingSeason : 'qqqq',
      ReceivingIssuingCollection : 'qqqq',
      ReceivingIssuingTheme : 'fg',
      DiscreteBatchNo : 'fg',
      AllocatedQuantity : 'fg',
      Nondeductible : 'fg',
    },
      {
        MaterialDocumnet: '5000658880',
        MaterialDocYear: '2022',
        materialDocItem: 'Item 2',
        identification: 'ID124',
        movementType: 'Type B',
        Material: 'Material B',
        Plant: 'Plant 2',
        storageLocation: 'Location 2',
        batch: 'Batch B',
        stockType: 'Type 2',
        supplier: 'Supplier B',
        currency: 'EUR',
        amountInLocCur: '200',
        valuationType: 'Type B',
        quantity: 100,
        baseUnitofMeasure: 'kg',
        qtyinunitofentry: '20',
        unitofEntry: 'unit',
        qtyinOPUn: '10',
        orderPriceUnit: 'NOS',
        purchaseOrder: '4500167423',
        Item: '1',
        FiscYearRefDoc: '2022',
        ReferenceDocument: '5000658879',
        ReferenceDocItem: '1',
        MaterialDocItem: '0',
        DeliveryCompleted: 'X',
        Text: 'S035',
        Goodsrecipient: 'p.srinivas',
        ControllingArea: '1000',
        FiscalYear: '2022',
        CompanyCode: '1000',
        Statisticallyrelev: '2',
        ReceivingMaterial: 'one',
      Receivingplant: 'ss',
      Receivingstorloc: 'a',
      ReceivingBatch: 's',
      RestrictedUse: 'q',
      Statkeytfrbatch: 's',
      Spindstocktfr: 'q',
      Movementindicator:  'q',
      Consumption: 'q',
      ReceiptIndicator: 'w',
      GRnonvaluated: '',
      Noofpallets: '',
      WarehouseNumber:  '',
      StorageType: 'q',
      StorageBin: '',
      StockCategory: 'q',
      MovementType: '',
      TRNumber: '1',
      TRItem: '1',
      PostinginWM: '1',
      Intstpostsource: 'q',
      Interimstorpdest: 'q',
      Dynamicstoragebin: '',
      PostingChangeNumber: '1',
      TransferPriority: '1',
      TransferOrderNumber: '1',
      NumberofGRSlips: '1',
      ReasonforMovement: 'q',
      CompliancewithShippingInstr : '',
      ShippingInstr : '',
      RealEstateKey : '',
      CostObject : '',
      ProfitabSegmtNo : '',
      ProfitCenter : '',
      WBSElement : '',
      Network : '',
      Routingnumberforoperations : '',
      Counter : '',
      Orderitemnumber : '',
      Partner : '',
      Commitmentitem : '',
      GLAccount : '',
      Qtyinorderunit : '',
      OrderUnit : '',
      RevGRdespiteIR : '',
      Vendor : '',
      RefSD : '',
      Addittext3 : '',
      TicketDate : '',
      TicketNO : '',
      TicketStatus : '',
      VendorName : '',
      VendorGSTIN : '',
      Remarks : '',
      ExtAmountinLocalCurrency : '',
      SeasoSalesValueincVATnYear : '',
      Promotion : '',
      SeqNoofAccountAssgt : 'f',
      SLEDBBD : 0,
      Internalobjectno : '',
      SalesValue : '',
      PartnerProfitCtr : '',
      Recordtype : '',
      Fund : '',
      FundsCenter : '',
      StockMaterial : '',
      Receivingmaterial : '',
      Quantitystring : '',
      ValueString : '',
      Quantityupdating : '',
      Valueupdating : '',   
      Totalvaluatedstockbeforetheposting  : '',          
      Totlvalbfposting : '2e',
      Pricecontrol : '2e',
      FunctionalArea : '2e',
      Referencedate : '2e',
      SalesvaluewoVAT : '2e',
      ReferenceDate : '2e',
      AutomaticPO : '2e',
      DelNoteQuantity : '2e',
      DeliveryNoteUnit : '2e',
      Specstkvaluation : '2e',
      InspectionStatusinGRDocument : '2e',
      Originallineitem : '2e',
      Altbaseamount : '2e',
      TaxCode : '2e',
      TaxJurisdiction : '2e',
      MPNmaterial : '2e',
      Goodsissuerevaluationperformed : '2e',
      Taxcode : 'wq',
      DateofManufacture : 'wq',
      MatStagingIndicat : 'wq',
      Salesorder : 'wq',
      Salesorderitem : 'wq',
      WBSelement : 'wq',
      Calcnofvalueopen : 'wq',
      AccountingIndicator : 'wq',
      BusinessProcess : 'wq',
      SupplyingVendor : 'wq',
      ActivityType : 'wq',
      Vendorstockvaluation : 'wq',
      Grant : 'wq',
      StockTypeModif : 'wq',
      GTSStockType : 'wq',
      EarmarkedFunds : 'wq',
      DocumentItem : 'wq',
      MultipleAccountAssignment : 'wq',
      TransEventType : 'qqqq',
      PostingDate : 'qqqq',
      EntryDate : 'qqqq',
      TimeofEntry : 'qqqq',
      UserName : 'qqqq',
      Reference : 'qqqq',
      TransactionCode : 'qqqq',
      Delivery : 'qqqq',
      item : 'qqqq',
      StockSegment : 'qqqq',
      ReceivingStockSegment : 'qqqq',
      RequirementSegment : 'qqqq',
      EDStatus : 'qqqq',
      Username : 'qqqq',
      ChangedOn : 'qqqq',
      Time : 'qqqq',
      Ownerofstock : 'qqqq',
      SeasonYear : 'qqqq',
      Season : 'qqqq',
      Collection : 'qqqq',
      Theme : 'qqqq',
      ReceivingIssuingSeasonYear : 'qqqq',      
      ReceivingIssuingSeason : 'qqqq',
      ReceivingIssuingCollection : 'qqqq',
      ReceivingIssuingTheme : 'fg',
      DiscreteBatchNo : 'fg',
      AllocatedQuantity : 'fg',
      Nondeductible : 'fg'
    },
    {
      MaterialDocumnet: '5000658881',
      MaterialDocYear: '2021',
      materialDocItem: 'Item 3',
      identification: 'ID125',
      movementType: 'Type B',
      Material: 'Material B',
      Plant: 'Plant 3',
      storageLocation: 'Location 3',
      batch: 'Batch C',
      stockType: 'Type 3',
      supplier: 'Supplier C',
      currency: 'EUR',
      amountInLocCur: '300',
      valuationType: 'Type C',
      quantity: 600,
      baseUnitofMeasure: 'kg',
      qtyinunitofentry: '20',
      unitofEntry: 'unit',
      qtyinOPUn: '10',
      orderPriceUnit: 'NOS',
      purchaseOrder: '4500167423',
      Item: '1',
      FiscYearRefDoc: '2022',
      ReferenceDocument: '5000658879',
      ReferenceDocItem: '1',
      MaterialDocItem: '0',
      DeliveryCompleted: 'X',
      Text: 'S035',
      Goodsrecipient: 'p.srinivas',
      ControllingArea: '1000',
      FiscalYear: '2022',
      CompanyCode: '1000',
      Statisticallyrelev: '3',
      ReceivingMaterial: 'one',
      Receivingplant: 'ss',
      Receivingstorloc: 'a',
      ReceivingBatch: 's',
      RestrictedUse: 'q',
      Statkeytfrbatch: 's',
      Spindstocktfr: 'q',
      Movementindicator:  'q',
      Consumption: 'q',
      ReceiptIndicator: 'w',
      GRnonvaluated: '',
      Noofpallets: '',
      WarehouseNumber:  '',
      StorageType: 'q',
      StorageBin: '',
      StockCategory: 'q',
      MovementType: '',
      TRNumber: '1',
      TRItem: '1',
      PostinginWM: '1',
      Intstpostsource: 'q',
      Interimstorpdest: 'q',
      Dynamicstoragebin: '',
      PostingChangeNumber: '1',
      TransferPriority: '1',
      TransferOrderNumber: '1',
      NumberofGRSlips: '1',
      ReasonforMovement: 'q',
      CompliancewithShippingInstr : '',
      ShippingInstr : '',
      RealEstateKey : '',
      CostObject : '',
      ProfitabSegmtNo : '',
      ProfitCenter : '',
      WBSElement : '',
      Network : '',
      Routingnumberforoperations : '',
      Counter : '',
      Orderitemnumber : '',
      Partner : '',
      Commitmentitem : '',
      GLAccount : '',
      Qtyinorderunit : '',
      OrderUnit : '',
      RevGRdespiteIR : '',
      Vendor : '',
      RefSD : '',
      Addittext3 : '',
      TicketDate : '',
      TicketNO : '',
      TicketStatus : '',
      VendorName : '',
      VendorGSTIN : '',
      Remarks : '',
      ExtAmountinLocalCurrency : '',
      SeasoSalesValueincVATnYear : '',
      Promotion : '',
      SeqNoofAccountAssgt : 'f',
      SLEDBBD : 0,
      Internalobjectno : '',
      SalesValue : '',
      PartnerProfitCtr : '',
      Recordtype : '',
      Fund : '',
      FundsCenter : '',
      StockMaterial : '',
      Receivingmaterial : '',
      Quantitystring : '',
      ValueString : '',
      Quantityupdating : '',
      Valueupdating : '',   
      Totalvaluatedstockbeforetheposting  : '',          
      Totlvalbfposting : '2e',
      Pricecontrol : '2e',
      FunctionalArea : '2e',
      Referencedate : '2e',
      SalesvaluewoVAT : '2e',
      ReferenceDate : '2e',
      AutomaticPO : '2e',
      DelNoteQuantity : '2e',
      DeliveryNoteUnit : '2e',
      Specstkvaluation : '2e',
      InspectionStatusinGRDocument : '2e',
      Originallineitem : '2e',
      Altbaseamount : '2e',
      TaxCode : '2e',
      TaxJurisdiction : '2e',
      MPNmaterial : '2e',
      Goodsissuerevaluationperformed : '2e',
      Taxcode : 'wq',
      DateofManufacture : 'wq',
      MatStagingIndicat : 'wq',
      Salesorder : 'wq',
      Salesorderitem : 'wq',
      WBSelement : 'wq',
      Calcnofvalueopen : 'wq',
      AccountingIndicator : 'wq',
      BusinessProcess : 'wq',
      SupplyingVendor : 'wq',
      ActivityType : 'wq',
      Vendorstockvaluation : 'wq',
      Grant : 'wq',
      StockTypeModif : 'wq',
      GTSStockType : 'wq',
      EarmarkedFunds : 'wq',
      DocumentItem : 'wq',
      MultipleAccountAssignment : 'wq',
      TransEventType : 'qqqq',
      PostingDate : 'qqqq',
      EntryDate : 'qqqq',
      TimeofEntry : 'qqqq',
      UserName : 'qqqq',
      Reference : 'qqqq',
      TransactionCode : 'qqqq',
      Delivery : 'qqqq',
      item : 'qqqq',
      StockSegment : 'qqqq',
      ReceivingStockSegment : 'qqqq',
      RequirementSegment : 'qqqq',
      EDStatus : 'qqqq',
      Username : 'qqqq',
      ChangedOn : 'qqqq',
      Time : 'qqqq',
      Ownerofstock : 'qqqq',
      SeasonYear : 'qqqq',
      Season : 'qqqq',
      Collection : 'qqqq',
      Theme : 'qqqq',
      ReceivingIssuingSeasonYear : 'qqqq',      
      ReceivingIssuingSeason : 'qqqq',
      ReceivingIssuingCollection : 'qqqq',
      ReceivingIssuingTheme : 'fg',
      DiscreteBatchNo : 'fg',
      AllocatedQuantity : 'fg',
      Nondeductible : 'fg',
    }
];

export { tableData };