const tableData = [
    {
        MaterialDocumnet: '5000658879',
        MaterialDocYear: '2023',
        materialDocItem: 'Item 1',
        identification: 'ID123',
        movementType: 'Type A',
        Material: 'Material A',
        Plant: 'Plant 1',
        storageLocation: 'Location 1',
        batch: 'Batch A',
        stockType: 'Type 1',
        supplier: 'Supplier A',
        currency: 'USD',
        amountInLocCur: '100',
        valuationType: 'Type A',
        quantity: 50,
        baseUnitofMeasure: 'kg',
        qtyinunitofentry: '10',
        unitofEntry: 'unit',
        qtyinOPUn: '5',
        orderPriceUnit: 'NOS',
        purchaseOrder: '4500167423',
        Item: '1',
        FiscYearRefDoc: '2022',
        ReferenceDocument: '5000658879',
        ReferenceDocItem: '1',
        MaterialDocItem: '0',
        DeliveryCompleted: 'X',
        Text: 'S035',
        Goodsrecipient: 'p.srinivas',
        ControllingArea: '1000',
        FiscalYear: '2022',
        CompanyCode: '1000',
        Statisticallyrelev: '2'
      },
      {
        MaterialDocumnet: '5000658880',
        MaterialDocYear: '2022',
        materialDocItem: 'Item 2',
        identification: 'ID124',
        movementType: 'Type B',
        Material: 'Material B',
        Plant: 'Plant 2',
        storageLocation: 'Location 2',
        batch: 'Batch B',
        stockType: 'Type 2',
        supplier: 'Supplier B',
        currency: 'EUR',
        amountInLocCur: '200',
        valuationType: 'Type B',
        quantity: 100,
        baseUnitofMeasure: 'kg',
        qtyinunitofentry: '20',
        unitofEntry: 'unit',
        qtyinOPUn: '10',
        orderPriceUnit: 'NOS',
        purchaseOrder: '4500167423',
        Item: '1',
        FiscYearRefDoc: '2022',
        ReferenceDocument: '5000658879',
        ReferenceDocItem: '1',
        MaterialDocItem: '0',
        DeliveryCompleted: 'X',
        Text: 'S035',
        Goodsrecipient: 'p.srinivas',
        ControllingArea: '1000',
        FiscalYear: '2022',
        CompanyCode: '1000',
        Statisticallyrelev: '2'
    },
    {
      MaterialDocumnet: '5000658881',
      MaterialDocYear: '2021',
      materialDocItem: 'Item 3',
      identification: 'ID125',
      movementType: 'Type B',
      Material: 'Material B',
      Plant: 'Plant 3',
      storageLocation: 'Location 3',
      batch: 'Batch C',
      stockType: 'Type 3',
      supplier: 'Supplier C',
      currency: 'EUR',
      amountInLocCur: '300',
      valuationType: 'Type C',
      quantity: 600,
      baseUnitofMeasure: 'kg',
      qtyinunitofentry: '20',
      unitofEntry: 'unit',
      qtyinOPUn: '10',
      orderPriceUnit: 'NOS',
      purchaseOrder: '4500167423',
      Item: '1',
      FiscYearRefDoc: '2022',
      ReferenceDocument: '5000658879',
      ReferenceDocItem: '1',
      MaterialDocItem: '0',
      DeliveryCompleted: 'X',
      Text: 'S035',
      Goodsrecipient: 'p.srinivas',
      ControllingArea: '1000',
      FiscalYear: '2022',
      CompanyCode: '1000',
      Statisticallyrelev: '3'
  }
];

export { tableData };